use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{anyhow, bail, Context, Result};

use crate::search::Package;

pub struct GenerateResult {
    pub flake_path: PathBuf,
    pub packages: Vec<String>,
    pub direnv_allowed: bool,
    pub direnv_message: String,
}

pub fn generate(
    target_dir: &Path,
    packages: &[Package],
    channel: &str,
    force: bool,
) -> Result<GenerateResult> {
    if packages.is_empty() {
        bail!("basket is empty — add packages with Space first");
    }

    std::fs::create_dir_all(target_dir)
        .with_context(|| format!("create {}", target_dir.display()))?;

    let flake_path = target_dir.join("flake.nix");
    let envrc_path = target_dir.join(".envrc");

    if !force {
        if flake_path.exists() {
            bail!(
                "flake.nix already exists in {} (press G to overwrite)",
                target_dir.display()
            );
        }
        if envrc_path.exists() {
            let existing = std::fs::read_to_string(&envrc_path).unwrap_or_default();
            if !existing.contains("use flake") {
                bail!(
                    ".envrc already exists and is not a flake envrc (press G to overwrite)"
                );
            }
        }
    }

    let attrs: Vec<&str> = packages.iter().map(|p| p.attr_name.as_str()).collect();
    let flake = render_flake(&attrs, channel);
    let envrc = "use flake\n";

    std::fs::write(&flake_path, flake)
        .with_context(|| format!("write {}", flake_path.display()))?;
    std::fs::write(&envrc_path, envrc)
        .with_context(|| format!("write {}", envrc_path.display()))?;

    let (direnv_allowed, direnv_message) = run_direnv_allow(target_dir);

    Ok(GenerateResult {
        flake_path,
        packages: attrs.into_iter().map(str::to_string).collect(),
        direnv_allowed,
        direnv_message,
    })
}

fn render_flake(attrs: &[&str], channel: &str) -> String {
    let nixpkgs_url = match channel {
        "unstable" => "github:NixOS/nixpkgs/nixos-unstable".to_string(),
        other => format!("github:NixOS/nixpkgs/nixos-{other}"),
    };

    let mut pkgs_list = String::new();
    for attr in attrs {
        pkgs_list.push_str(&format!("          {attr}\n"));
    }

    format!(
        r#"{{
  description = "Generated by nixpick";

  inputs.nixpkgs.url = "{nixpkgs_url}";

  outputs = {{ nixpkgs, ... }}:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${{system}});
    in {{
      devShells = forAllSystems (pkgs: {{
        default = pkgs.mkShell {{
          packages = with pkgs; [
{pkgs_list}          ];
        }};
      }});
    }};
}}
"#
    )
}

fn run_direnv_allow(dir: &Path) -> (bool, String) {
    match Command::new("direnv")
        .args(["allow", "."])
        .current_dir(dir)
        .output()
    {
        Ok(out) if out.status.success() => (true, "direnv allow: ok".into()),
        Ok(out) => {
            let stderr = String::from_utf8_lossy(&out.stderr);
            (
                false,
                format!(
                    "direnv allow failed: {}",
                    stderr.trim().lines().next().unwrap_or("unknown error")
                ),
            )
        }
        Err(e) => (
            false,
            format!("direnv not available ({e}) — run `direnv allow` manually"),
        ),
    }
}

pub fn merge_into_existing(
    target_dir: &Path,
    packages: &[Package],
    channel: &str,
) -> Result<GenerateResult> {
    generate(target_dir, packages, channel, true)
}

#[allow(dead_code)]
pub fn validate_attr(attr: &str) -> Result<()> {
    if attr.is_empty()
        || attr.contains(|c: char| !(c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-'))
    {
        return Err(anyhow!("invalid package attr: {attr}"));
    }
    Ok(())
}
